# Generated by Django 6.1 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0010_edi835file_d35file_client__bf8b7d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='use_default',
            field=models.BooleanField(default=False, help_text='Whether to use default SFTP settings'),
        ),
    ]
