# Generated by Django 6.1 on 2026-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edi835", "0012_sftpconfig_outbound_ssh_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sftpconfig",
            name="outbound_password",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sftpconfig",
            name="ssh_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
