# Generated by Django 6.1 on 2026-08-27 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_totp_enabled'),
        ('edi835', '0013_alter_sftpconfig_outbound_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIRClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_sequence', models.PositiveIntegerField()),
                ('claim_control_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('record_type', models.CharField(blank=True, default='', max_length=2)),
                ('member_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('patient_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('patient_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=8)),
                ('claim_status', models.CharField(blank=True, default='', max_length=10)),
                ('primary_reason', models.CharField(blank=True, default='', max_length=10)),
                ('service_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=1)),
                ('header_raw', models.CharField(max_length=334)),
                ('segment_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mir_claim',
                'ordering': ['claim_sequence'],
            },
        ),
        migrations.CreateModel(
            name='MIRClaimChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveSmallIntegerField()),
                ('service_start_number', models.PositiveIntegerField(default=0)),
                ('service_end_number', models.PositiveIntegerField(default=0)),
                ('services_in_chunk', models.PositiveSmallIntegerField(default=0)),
                ('physical_row_number', models.PositiveIntegerField()),
                ('raw_row', models.TextField()),
                ('row_length', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mir_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='edi835.mirclaim')),
            ],
            options={
                'db_table': 'mir_claim_chunk',
                'ordering': ['physical_row_number'],
            },
        ),
        migrations.CreateModel(
            name='MIRFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mir_filename', models.CharField(max_length=255)),
                ('original_835_filename', models.TextField(blank=True, default='')),
                ('file_content', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('physical_row_count', models.PositiveIntegerField(default=0)),
                ('service_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PUSHED', 'Pushed'), ('PUSH_FAILED', 'Push failed')], default='GENERATED', max_length=20)),
                ('converted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mir_files', to='accounts.client')),
                ('source_835', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mir_file', to='edi835.edi835file')),
            ],
            options={
                'db_table': 'mir_file',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.AddField(
            model_name='mirclaim',
            name='mir_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='edi835.mirfile'),
        ),
        migrations.CreateModel(
            name='MIRServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_sequence', models.PositiveIntegerField()),
                ('chunk_service_sequence', models.PositiveSmallIntegerField()),
                ('procedure_code', models.CharField(blank=True, default='', max_length=64)),
                ('service_date', models.CharField(blank=True, default='', max_length=8)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('patient_liability', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason_code', models.CharField(blank=True, default='', max_length=10)),
                ('service_raw', models.CharField(max_length=303)),
                ('segment_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mir_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='edi835.mirclaimchunk')),
                ('mir_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='edi835.mirclaim')),
            ],
            options={
                'db_table': 'mir_service_line',
                'ordering': ['service_sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='mirclaimchunk',
            constraint=models.UniqueConstraint(fields=('mir_claim', 'chunk_number'), name='uniq_mir_claim_chunk'),
        ),
        migrations.AddConstraint(
            model_name='mirclaimchunk',
            constraint=models.CheckConstraint(condition=models.Q(('services_in_chunk__gte', 0), ('services_in_chunk__lte', 50)), name='mir_chunk_max_50_services'),
        ),
        migrations.AddIndex(
            model_name='mirfile',
            index=models.Index(fields=['client', '-converted_at'], name='mir_file_client__51c206_idx'),
        ),
        migrations.AddIndex(
            model_name='mirfile',
            index=models.Index(fields=['mir_filename'], name='mir_file_mir_fil_0a568d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mirclaim',
            constraint=models.UniqueConstraint(fields=('mir_file', 'claim_sequence'), name='uniq_mir_claim_sequence'),
        ),
        migrations.AddConstraint(
            model_name='mirserviceline',
            constraint=models.UniqueConstraint(fields=('mir_claim', 'service_sequence'), name='uniq_mir_service_sequence'),
        ),
        migrations.AddConstraint(
            model_name='mirserviceline',
            constraint=models.UniqueConstraint(fields=('mir_chunk', 'chunk_service_sequence'), name='uniq_mir_chunk_service_sequence'),
        ),
        migrations.AddConstraint(
            model_name='mirserviceline',
            constraint=models.CheckConstraint(condition=models.Q(('chunk_service_sequence__gte', 1), ('chunk_service_sequence__lte', 50)), name='mir_service_position_1_50'),
        ),
    ]
