# Generated by Django 6.1 on 2026-08-27 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_totp_enabled'),
        ('edi835', '0014_mir_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RECONFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_content', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('service_count', models.PositiveIntegerField(default=0)),
                ('total_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_files', to='accounts.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_recon_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recon_file',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RECONClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_sequence', models.PositiveIntegerField()),
                ('claim_control_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('member_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('patient_control_number', models.CharField(blank=True, default='', max_length=100)),
                ('record_type', models.CharField(blank=True, default='', max_length=30)),
                ('claim_status', models.CharField(blank=True, default='', max_length=30)),
                ('service_count', models.PositiveIntegerField(default=0)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('allowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('service_from_date', models.CharField(blank=True, default='', max_length=10)),
                ('service_to_date', models.CharField(blank=True, default='', max_length=10)),
                ('raw_record', models.TextField(blank=True, default='')),
                ('segment_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_claims', to='accounts.client')),
                ('recon_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='edi835.reconfile')),
            ],
            options={
                'db_table': 'recon_claim',
                'ordering': ['claim_sequence'],
            },
        ),
        migrations.CreateModel(
            name='RECONProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('claims_created', models.PositiveIntegerField(default=0)),
                ('services_created', models.PositiveIntegerField(default=0)),
                ('invalid_records', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_processing_runs', to='accounts.client')),
                ('recon_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='edi835.reconfile')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recon_processing_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RECONProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('claim_control_number', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('raw_record', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recon_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_errors', to='edi835.reconfile')),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='edi835.reconprocessingrun')),
            ],
            options={
                'db_table': 'recon_processing_error',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='RECONServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_sequence', models.PositiveIntegerField()),
                ('source_row_number', models.PositiveIntegerField()),
                ('service_line_number', models.CharField(blank=True, default='', max_length=30)),
                ('procedure_code', models.CharField(blank=True, default='', max_length=50)),
                ('revenue_code', models.CharField(blank=True, default='', max_length=30)),
                ('service_from_date', models.CharField(blank=True, default='', max_length=10)),
                ('service_to_date', models.CharField(blank=True, default='', max_length=10)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('allowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason_code', models.CharField(blank=True, default='', max_length=30)),
                ('raw_service', models.TextField()),
                ('segment_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recon_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='edi835.reconclaim')),
                ('recon_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='edi835.reconfile')),
            ],
            options={
                'db_table': 'recon_service_line',
                'ordering': ['service_sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='reconfile',
            index=models.Index(fields=['client', '-uploaded_at'], name='recon_file_client__6e7e32_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfile',
            index=models.Index(fields=['client', 'status'], name='recon_file_client__be4995_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconfile',
            constraint=models.UniqueConstraint(fields=('client', 'file_hash'), name='uniq_client_recon_hash'),
        ),
        migrations.AddIndex(
            model_name='reconclaim',
            index=models.Index(fields=['client', 'claim_control_number'], name='recon_claim_client__c8d26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconclaim',
            constraint=models.UniqueConstraint(fields=('recon_file', 'claim_sequence'), name='uniq_recon_claim_sequence'),
        ),
        migrations.AddConstraint(
            model_name='reconserviceline',
            constraint=models.UniqueConstraint(fields=('recon_claim', 'service_sequence'), name='uniq_recon_service_sequence'),
        ),
    ]
