# Generated by Django 6.1 on 2026-08-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_client_mir_filename_format'),
        ('admin_panel', '0006_auditlog_admin_panel_client__809aad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmtpconfig',
            name='use_default',
            field=models.BooleanField(default=False, help_text='Whether to use default SMTP settings'),
        ),
        migrations.AlterField(
            model_name='clientsmtpconfig',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='accounts.client'),
        ),
    ]
