# Generated by Django 6.1 on 2026-08-24 10:16

from django.db import migrations


DEFAULT_STEPS = [
    (1,  "Mutual NDA signed",                                   "Upload signed NDA template to establish confidentiality agreement."),
    (2,  "Business associate agreement executed",               "Execute HIPAA compliant Business Associate Agreement."),
    (3,  "Security review returned to client",                  "Upload security audit review document."),
    (4,  "Contact Records",                                     "Designate client contact personnel and records."),
    (5,  "Claims system identified and verified",               "Identify client claims vendor software system."),
    (6,  "SMTP / Email Configuration",                          "Configure SMTP credentials to utilize for onboarding notifications."),
    (7,  "Delivery method agreed",                              "Configure secure transfer mechanism (SFTP, API drop)."),
    (8,  "Sample 835 received and validated",                   "Validate structural integrity of sample X12 835 file."),
    (9,  "Mapping rules written & configured",                  "Open Mapping Application to configure 835 conversion."),
    (10, "MIR Output Filename Format & Create User",            "Define output MIR file naming convention and create SFTP user logins."),
    (11, "Side-by-Side 835 Conversion Review",                  "Verify side-by-side conversion of sample 835 files."),
    (12, "Go-Live Safeguards Verification",                     "Confirm production cutover safeguards and monitoring."),
    (13, "Production Schedule",                                 "Define scheduled date and time to go live."),
    (14, "Go-Live / Final Verification",                        "Attach email conversation confirmation."),
    (15, "Production Delivery Sign-Off / Conclude Onboarding",  "Monitor first live 835 delivery and conclude onboarding."),
]


def seed_steps(apps, schema_editor):
    OnboardingStepDefinition = apps.get_model('admin_panel', 'OnboardingStepDefinition')

    existing = {s.step_number: s for s in OnboardingStepDefinition.objects.all()}

    for num, title, desc in DEFAULT_STEPS:
        if num in existing:
            step = existing[num]
            if step.title != title or step.description != desc:
                step.title = title
                step.description = desc
                step.save(update_fields=['title', 'description'])
        else:
            OnboardingStepDefinition.objects.create(
                step_number=num, title=title, description=desc
            )

    # Remove any extra steps beyond the canonical 15
    valid_numbers = {num for num, _, _ in DEFAULT_STEPS}
    OnboardingStepDefinition.objects.exclude(step_number__in=valid_numbers).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_clientsmtpconfig_use_default_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_steps, migrations.RunPython.noop),
    ]
