# Generated by Django 6.1 on 2026-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_rename_onboarding_validation_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsmtpconfig",
            name="smtp_password",
            field=models.TextField(blank=True),
        ),
    ]
