# Generated by Django 6.1 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientstepcomment_client_step_client__ab3a49_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mir_filename_format',
            field=models.CharField(default='MIROUT_YYYY_MMDD_.MIR', help_text='Preferred MIR filename format', max_length=255),
        ),
    ]
