# Generated by Django 6.1 on 2026-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_client_mir_filename_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
