# Generated by Django 6.1 on 2026-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_totp_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
