# Generated by Django 5.2.17 on 2026-09-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_login_lockout_fields'),
        ('accounts', '0022_webauthnchallenge_webauthncredential'),
    ]

    operations = [
    ]
